### PR TITLE
Prettify editor

### PR DESCRIPTION
**Pull request by deemp**

### CODE REVIEW

**Comment by deemp** [comment]
Current demo
image

**Comment by deemp** [comment]
@fizruk, please review

**Comment by deemp** [comment]
Moved html code to Haskell. Now runs with Jsaddle and looks almost the same as when compiled with ghcjs.

Issues:
- Scripts in `Main.hs` aren't loaded timely
- Link to a graph is broken when running with `Jsaddle`

**Comment by deemp** [comment]
* Add one primitive (int)
* Add EO code printing


* Use ^n (where n should be a natural number) for locators when printing to EO (may not be supported in EO)
* Use application to object (may not be supported in EO)
* See the review of the editor <a href="https://youtu.be/WBDxyfPxGbU">here</a>

**Comment by fizruk** [comment]
> Use `^n` (where n should be a natural number) for locators when printing to EO (may not be supported in EO)

Why not pretty-print `^4` as `^.^.^.^`, `^1` as `^`, and `^0` as `$` to match current EO syntax?

> Use application to object (may not be supported in EO)

Perhaps that should be supported in EO, if it indeed is not. Have you asked?

**Pull request merged**
